// <auto-generated />
namespace RhNetServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m00001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m00001));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101316533_m00001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
