// <auto-generated />
namespace RhNetServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m00003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m00003));
        
        string IMigrationMetadata.Id
        {
            get { return "202012092050386_m00003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
